/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IdeasIndexRouteImport } from './routes/ideas/index'
import { Route as IdeasNewIdeaIndexRouteImport } from './routes/ideas/newIdea/index'
import { Route as IdeasIdeaIdIndexRouteImport } from './routes/ideas/$ideaId/index'
import { Route as IdeasIdeaIdEditRouteImport } from './routes/ideas/$ideaId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasIndexRoute = IdeasIndexRouteImport.update({
  id: '/ideas/',
  path: '/ideas/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasNewIdeaIndexRoute = IdeasNewIdeaIndexRouteImport.update({
  id: '/ideas/newIdea/',
  path: '/ideas/newIdea/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasIdeaIdIndexRoute = IdeasIdeaIdIndexRouteImport.update({
  id: '/ideas/$ideaId/',
  path: '/ideas/$ideaId/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasIdeaIdEditRoute = IdeasIdeaIdEditRouteImport.update({
  id: '/ideas/$ideaId/edit',
  path: '/ideas/$ideaId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ideas': typeof IdeasIndexRoute
  '/ideas/$ideaId/edit': typeof IdeasIdeaIdEditRoute
  '/ideas/$ideaId': typeof IdeasIdeaIdIndexRoute
  '/ideas/newIdea': typeof IdeasNewIdeaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ideas': typeof IdeasIndexRoute
  '/ideas/$ideaId/edit': typeof IdeasIdeaIdEditRoute
  '/ideas/$ideaId': typeof IdeasIdeaIdIndexRoute
  '/ideas/newIdea': typeof IdeasNewIdeaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ideas/': typeof IdeasIndexRoute
  '/ideas/$ideaId/edit': typeof IdeasIdeaIdEditRoute
  '/ideas/$ideaId/': typeof IdeasIdeaIdIndexRoute
  '/ideas/newIdea/': typeof IdeasNewIdeaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ideas'
    | '/ideas/$ideaId/edit'
    | '/ideas/$ideaId'
    | '/ideas/newIdea'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ideas'
    | '/ideas/$ideaId/edit'
    | '/ideas/$ideaId'
    | '/ideas/newIdea'
  id:
    | '__root__'
    | '/'
    | '/ideas/'
    | '/ideas/$ideaId/edit'
    | '/ideas/$ideaId/'
    | '/ideas/newIdea/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IdeasIndexRoute: typeof IdeasIndexRoute
  IdeasIdeaIdEditRoute: typeof IdeasIdeaIdEditRoute
  IdeasIdeaIdIndexRoute: typeof IdeasIdeaIdIndexRoute
  IdeasNewIdeaIndexRoute: typeof IdeasNewIdeaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas/': {
      id: '/ideas/'
      path: '/ideas'
      fullPath: '/ideas'
      preLoaderRoute: typeof IdeasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas/newIdea/': {
      id: '/ideas/newIdea/'
      path: '/ideas/newIdea'
      fullPath: '/ideas/newIdea'
      preLoaderRoute: typeof IdeasNewIdeaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas/$ideaId/': {
      id: '/ideas/$ideaId/'
      path: '/ideas/$ideaId'
      fullPath: '/ideas/$ideaId'
      preLoaderRoute: typeof IdeasIdeaIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas/$ideaId/edit': {
      id: '/ideas/$ideaId/edit'
      path: '/ideas/$ideaId/edit'
      fullPath: '/ideas/$ideaId/edit'
      preLoaderRoute: typeof IdeasIdeaIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IdeasIndexRoute: IdeasIndexRoute,
  IdeasIdeaIdEditRoute: IdeasIdeaIdEditRoute,
  IdeasIdeaIdIndexRoute: IdeasIdeaIdIndexRoute,
  IdeasNewIdeaIndexRoute: IdeasNewIdeaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
